
platform :ios, '10.0'

target 'FlashChat' do
  
  use_frameworks!

  # Pods for FlashChat

    pod 'CLTypingLabel','~> 0.4.0'
    
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'IQKeyboardManagerSwift'

end
